# Generated by Django 3.0.5 on 2020-04-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailersubmission',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
